### ISSUE TITLE
장바구니 → 결제페이지

### ISSUE THREAD

**Issue by csm009177** [KDT-IaaS-Class-One-Group/KDT-IaaS-1team-ERP#19]

**Comment by kimwoojin123** [comment]
장바구니에서 여러 항목 결제 시 결제페이지의 로직/구조 변경이 필요.

현재 결제페이지는 상품상세에서 해당 상품의 정보만 받아오게 되어있음.

urlSearchParams 에서 여러 항목에 대한 정보를 주었을 때 전부 받아와서 나열시키고, 총 합을 마지막에 띄운 후, 그 정보로 결제하는 로직/구조 작성이 필요.
