### ISSUE TITLE
admin/ 상품 등록 페이지 / 이미지 등록 동적 기능 필요.

### ISSUE THREAD

**Issue by JungYoungSick** [KDT-IaaS-Class-One-Group/KDT-IaaS-1team-ERP#30]
현재 카테고리, 상품명, 가격, 재고, 입력 input이 만들어져 있다.
이미지 등록할 동적 기능이 필요하다.
<img width="256" alt="image" src="https://github.com/KDT-IaaS-Class-One-Group/KDT-IaaS-1team-ERP/assets/141981109/559e865c-202d-485d-a8df-6fb94d532cad">

**Comment by kimwoojin123** [comment]
해결완료
